name: Hello World

"on":
  workflow_dispatch:

permissions:
  contents: read

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - run: python hello_world_to_file.py
